# Generated by Django 3.0.8 on 2020-07-22 11:49

from django.db import migrations, models
import django.db.models.functions.text
import django_expression_index.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lexem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='lexem',
            index=django_expression_index.index.ExpressionIndex(expressions=[django.db.models.functions.text.Lower('surface')], name='django_native_searc_f899a8_idx'),
        ),
    ]
